spring:
  datasource:
    url: jdbc:mysql://localhost:3307/groovestreet?serverTimezone=UTC
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
# jpa:
# properties:
# hibernate:
# dialect: org.hibernate.dialect.MySQL8Dialect
# generate-ddl: true
# hibernate:
